### ISSUE TITLE
Reading the whole tape

### ISSUE THREAD

**Issue by patrikfejda** [aepsilon/turing-machine-viz#10]
Is there some workaround to read the whole tape once the machine run is done (e.g. console log or anything)

Lets run the following unary (`11=2, 111=3, 1111=4`) calculator A+B:
```yml
input: '111111$1111#'
blank: ' '
start state: look_for_1
table:
  look_for_1:
    '$': R
    1: {write: 'X', R: write_1}
  write_1:
    [1, $, '#']: R
    ' ': {write: '1', L: go_to_very_left}
  go_to_very_left:
    ['#', 1, $]: L
    'X': {R: look_for_1}
 ```
there is no way we can read what is behind the end:
![image](https://user-images.githubusercontent.com/55843553/161966392-5b3ee548-dba0-42c4-af8a-2694d5aa917f.png)

Any idea pls as a workaround for now ?

Maybe this issue would be worth consideration and some proper fix.

Thanks :)
